region = "us-east-1"
environment = "dev"
vpc_cidr = "10.100.0.0/16"
azs = ["us-east-1a", "us-east-1b", "us-east-1c"]
ami_id = "ami-0fa3fe0fa7920f68e" # example Amazon Linux 2 (replace for your region)
instance_type = "t3.micro"
min_asg = 1
max_asg = 4
images_bucket = "group10-acs730-dev-images"
team_names = "Winlyn Luena, John Vernard Canlas, Maedeh Farahmand Dehghanpour, Shahab Ghahhari, Heracleo Elbina "
owner = "Group10"
project = "Group10"
allowed_ssh_cidr = "99.209.173.182/32"
